# bitbucket-pvc.yaml
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: bitbucket-data
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi  # Adjust the storage size as needed
---
# bitbucket-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: bitbucket
spec:
  replicas: 1  # You can adjust the number of replicas
  selector:
    matchLabels:
      app: bitbucket
  template:
    metadata:
      labels:
        app: bitbucket
    spec:
      containers:
        - name: bitbucket
          image: atlassian/bitbucket:latest
          ports:
            - containerPort: 7990
              name: http
          resources:
            requests:
              memory: "1Gi"
              cpu: "500m"
          volumeMounts:
            - name: bitbucket-data
              mountPath: /var/atlassian/application-data/bitbucket
      volumes:
        - name: bitbucket-data
          persistentVolumeClaim:
            claimName: bitbucket-data
---
# bitbucket-service.yaml
apiVersion: v1
kind: Service
metadata:
  name: bitbucket
spec:
  type: ClusterIP
  ports:
    - protocol: TCP
      name: web
      port: 7990
      targetPort: 7990
    - protocol: TCP
      name: ssh
      port: 7999
      targetPort: 7999
  selector:
    app: bitbucket  # Match the labels in your bitbucket deployment